repos:
- repo: https://github.com/FrankMaverick/dati-semantic-cookiecutter
  rev: 4f268eddac182d59e3da44c5577ec466764bb340
  hooks:
  - id: check-repo-structure
    args: ["assets/controlled-vocabularies/", "assets/ontologies/", "assets/schemas/"]
  - id: check-filename-format
    args: ["assets/controlled-vocabularies/", "assets/ontologies/", "assets/schemas/"]
  - id: check-filenames-match-uri
    args: ["assets/controlled-vocabularies/", "assets/ontologies/", "assets/schemas/"]
  - id: check-filenames-match-directories
    args: ["assets/controlled-vocabularies/", "assets/ontologies/", "assets/schemas/"]
  - id: check-supported-files
    args: ["assets/controlled-vocabularies/", "assets/ontologies/", "assets/schemas/"]
  - id: check-versioning-pattern
    args: ["assets/controlled-vocabularies/", "assets/ontologies/", "assets/schemas/"]

#
# Semantic checks.
#
- repo: https://github.com/teamdigitale/json-semantic-playground
  rev: 0b4ad4cc883a49878fdfd4539e694ae56b041e29
  hooks:
  - id: validate-csv
    files: >-
      ^assets\/controlled-vocabularies/.*\.csv
  - id: validate-oas-schema
    files: >-
      ^assets\/schemas\/.*.oas3.yaml
  - id: validate-turtle
    files: >-
      ^assets\/ontologies\/[^\/]+\/latest\/.*\.ttl
  - id: validate-turtle
    files: >-
      ^assets\/controlled-vocabularies\/.*\.ttl
  - id: validate-turtle
    files: >-
      ^assets\/schemas\/.*\.ttl